spring:

  application:
    name: mealtime-api
  config:
    import: env.properties
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  sql:
    init:
      mode: always

jwt:
  auth:
    converter:
      resource-id: mealtime-web
logging:
  file:
    name: logs/log.log
    max-size: 1MB
    total-size-cap: 10MB
    max-history: 30
  level:
    org.springframework.security: DEBUG
  pattern:
    rolling-file-name: logs/log-%d{yyyy-MM-dd}.%i.log
  path: logs

server:
  port: '8081'
  servlet:
    context-path: /api
services:
  recipe-importer:
    endpoint: ${RECIPE_IMPORTER_SERVICE_ENDPOINT}